// src/app/oc/page.tsx
import PageContainer from '@mae/components/layout/PageContainer'
import React from 'react'
import Image from 'next/image';
import Button from '@mae/components/Button';

export default function Donate() {
  return (
    <PageContainer>
      <h1 className='text-4xl font-semibold'>Page Work in Progress!</h1>
      <p>For now, here's a static refsheet.</p>
      <Button href='https://i.mae.wtf/dqdgox.png' text='Download High Quality' className='w-fit' icon='bx bx-download mr-2'></Button>
      <Image src="https://i.mae.wtf/dqdgox.png" width={400} height={100} alt="mae refsheet"></Image>
    </PageContainer>
  )
}

// src/routes/(main)/oc/+page.svelte
<script>
	import PageContainer from '@mae/components/core/PageContainer.svelte';
	import PageHeader from '@mae/components/core/PageHeader.svelte';
	import Button from '@mae/components/ui/Button.svelte';
</script>

<PageContainer>
	<PageHeader title="🎏 my oc (mae)"></PageHeader>
	<p class="text-4xl font-semibold">Page Work in Progress!</p>
	<p>For now, here's a static refsheet.</p>
	<Button
		href="https://cdn.mae.wtf/maeoc/refsheet-2024.png"
		text="Download High Quality"
		className="w-fit"
		icon="bx bx-download mr-2"
	></Button>
	<img
		src="https://cdn.mae.wtf/maeoc/refsheet-2024.png"
		width={400}
		height={100}
		alt="mae refsheet"
	/>
</PageContainer>
