// src/components/core/Footer.svelte
<script lang="ts">
	import dayjs from 'dayjs';
</script>

<footer class="flex justify-center z-10 sticky">
	<div
		class="w-full p-8 border-0 shadow-vi-900/70 bg-vi-900 flex justify-center"
		style="box-shadow: 0px 0px 32px 8px var(--tw-shadow-color)"
	>
		<div class="mx-8 max-w-[1024px] w-full text-sm flex flex-col-reverse gap-4 sm:flex-row">
			<div class="flex flex-col w-1/3">
				<h4 class="font-bold text-2xl">mae</h4>
				<p class="text-xs">
					©️ 2018-{dayjs().year()} vimae
				</p>
				<p></p>
				<a href="https://github.com/vimaexd/website">source code</a>
				<a href="/privacy">privacy</a>
			</div>
			<div class="flex gap-16 sm:justify-end w-full">
				<div class="flex flex-col gap-1 text-[1.05rem]">
					<h3 class="font-semibold text-2xl">About</h3>
					<a href="/">Home</a>
					<a href="/gear">Gear</a>
					<a href="/donate">Donate</a>
					<a href="/contact">Contact</a>
				</div>
				<div class="flex flex-col gap-1 text-[1.05rem]">
					<h3 class="font-semibold text-2xl">Media</h3>
					<a href="/blog">Blog</a>
					<a href="/music">Music</a>
					<a href="/oc">My OC</a>
				</div>
				<div class="flex flex-col gap-1 text-[1.05rem]">
					<h3 class="font-semibold text-2xl">More</h3>
					<a href="https://misc.mae.wtf">Misc</a>
					<a href="https://misc.mae.wtf">RSS feed</a>
				</div>
			</div>
		</div>
	</div>
</footer>

// src/components/core/Footer.tsx
import dayjs from 'dayjs'
import Link from 'next/link'
import React from 'react'

export default function Footer() {
  return (
    <footer className='flex justify-center z-10 sticky'>
      <div className='w-full p-8 border-0 shadow-ctp-mantle bg-ctp-base flex justify-center'
      style={{
        boxShadow: "0px 0px 32px 8px var(--tw-shadow-color)",
      }}>
        <div className='mx-8 max-w-[1024px] w-full text-sm flex flex-col-reverse gap-4 sm:flex-row'>
          <div className='flex flex-col w-1/3'>
            <h4 className='font-bold text-2xl'>mae</h4>
            <p className='text-xs'>
              ©️ 2018-{dayjs().year()} vimae. thank you! {"<3"}
            </p>
            <p>

            </p>
            <Link href="https://github.com/vimaexd/website">
                source code
            </Link>
            <Link href="/privacy">
                privacy
            </Link>
          </div>
          <div className='flex gap-16 sm:justify-end w-full'>
            <div className='flex flex-col'>
              <h3 className='font-semibold text-lg'>About</h3>
              <Link href="/">
                Home
              </Link>
              <Link href="/gear">
                Gear
              </Link>
              <Link href="/donate">
                Donate
              </Link>
              <Link href="/contact">
                Contact
              </Link>
            </div>
            <div className='flex flex-col'>
              <h3 className='font-semibold text-lg'>Media</h3>
              <Link href="/music">
                Music
              </Link>
              <Link href="/oc">
                My OC (old)
              </Link>
            </div>
            <div className='flex flex-col'>
              <h3 className='font-semibold text-lg'>Services</h3>
              <Link href="https://misc.mae.wtf">
                misc
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
