// src/components/core/Navbar.tsx
"use client";
import { animate } from "animejs";
import Link from "next/link";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import Button, { ButtonStyle } from "@mae/components/ui/Button";
import VimaeLogo from "@mae/assets/icons/logo-vimae";
import VimaeLogoMono from "@mae/assets/icons/logo-vimae-mono";
import { usePathname } from "next/navigation";
import { useAtom } from "jotai";
import { transparentNavbar } from "@mae/store/transparentNavbar";
import NavbarStars from "@mae/components/subnavigation/StarryBg";

const navOptions: { [path: string]: string } = {
    "/": "🏠 Home",
    "/blog": "📝 Blog",
    "/projects": "📦 Projects",
    "/music": "🎵 Music",
    "/gear": "⌨️ Gear",
    "/contact": "📱 Contact",
    "/donate": "💰 Donate",
};

export default function Navbar({ version }: { version: string }) {
    const pathname = usePathname();
    const [isTransparentPage, setTransparentPage] = useAtom(transparentNavbar);

    // when navigating to a new page, set the transparent state to default
    useEffect(() => {
        setTransparentPage(false);
        if (bar.current) {
            setBarSize([bar.current.clientWidth, bar.current.clientHeight]);
        }
    }, [pathname, setTransparentPage]);

    const bar = useRef<HTMLDivElement>(null);
    const [menuVisible, setMenuVisible] = useState(false);

    const [barSize, setBarSize] = useState<number[]>([]);

    useLayoutEffect(() => {
        if (bar.current) {
            setBarSize([bar.current.clientWidth, bar.current.clientHeight]);
        }
    }, []);

    return (
        <nav
            className={`w-full lg:h-32 flex justify-center z-20 sticky bg-transparent`}
            ref={bar}
        >
            <NavbarStars barHeight={(pathname !== "/") ? barSize[1] : barSize[1] + 256} barWidth={barSize[0]} />
            <div className="w-[1024px] lg:px-0 h-full flex lg:flex-row flex-col lg:items-center py-4 lg:py-8 gap-4 lg:gap-0 z-10 md:px-8 px-4">
                <div className="flex flex-row items-center lg:justify-center justify-between space-x-4">
                    {(pathname !== "/") && (
                        <div>
                            <LogoText />
                            <h2 className="text-xs font-mono">v{version}</h2>
                        </div>
                    )}
                    <div className="ml-auto lg:hidden">
                        <i
                            className="bx bx-menu bx-md cursor-pointer anim-navbar-hamburger"
                            onClick={() => {
                                animate(".anim-navbar-hamburger", {
                                    rotateZ: [0, 180],
                                });
                                setMenuVisible(!menuVisible);
                            }}
                        ></i>
                    </div>
                </div>
                <div
                    className={`lg:ml-auto lg:flex lg:flex-row flex-col lg:justify-end flex-wrap gap-2 lg:w-8/12 anim-navbar-tray ${menuVisible ? "flex" : "hidden"}`}
                >
                    {Object.keys(navOptions).map((op) => (
                        <Button
                            key={op}
                            text={navOptions[op]}
                            href={op}
                            style={
                                pathname == op
                                    ? ButtonStyle.Active
                                    : ButtonStyle.Primary
                            }
                        />
                    ))}
                </div>
            </div>
        </nav>
    );
}

function LogoText() {
    const [isTransparentPage] = useAtom(transparentNavbar);

    return (
        <Link
            href="/"
            className="font-bold text-5xl tracking-tighter text-white"
            data-anim="logo"
        >
            {isTransparentPage ? (
                <VimaeLogoMono width="128px" height="fit" className="pb-2" />
            ) : (
                <VimaeLogo width="128px" height="fit" className="pb-2" />
            )}
        </Link>
    );
}

// src/components/core/Navbar.svelte
<script lang="ts">
	import { animate, createSpring } from 'animejs';
	import Button from '@mae/components/ui/Button.svelte';
	import LogoText from '@mae/components/brand/LogoText.svelte';
	import { version, dev } from '$app/environment';
	import { debounce } from '$lib/misc/utils';

	// TODO MAKE STARS

	let bar: HTMLElement;

	let isTransparentPage = false; // TODO: STORE
	let menuVisible = $state(false); // TODO: IMPLEMENT
	let stars = $state<number[][]>([]);
	let starsDone = $state(false);

	const _generateStars = () => {
		console.log('✨');
		if (!bar) return;
		const width = bar.offsetWidth;
		const height = bar.offsetHeight;

		let newStars = [];
		for (let i = 0; i < 8; i++) {
			let star = Math.floor(Math.random() * 4);
			let randX = Math.floor(Math.random() * (width - 16)) + 0;
			let randY = Math.floor(Math.random() * (height - 16));
			newStars.push([randX, randY, star]);
		}
		stars = newStars;
	};

	const generateStars = debounce(() => {
		_generateStars();
	}, 50);

	$effect(() => {
		if (!starsDone) {
			window.addEventListener('resize', () => {
				generateStars();
			});
			generateStars();
		}
	});
</script>

<nav
	class={`w-full lg:h-32 flex justify-center z-20 sticky ${isTransparentPage ? 'bg-transparent' : 'bg-vi-900'}`}
	bind:this={bar}
>
	<div
		class="absolute top-0 left-0 lg:w-[1024px] w-full opacity-60 z-0 text-clip"
		aria-hidden={true}
	>
		{#each stars as star, i}
			<img
				src={`/assets/stars/star_${star[2]}.png`}
				width={16}
				height={16}
				alt="star"
				class={'absolute ' + `anim_star`}
				style={`top: ${star[1]}px; left: ${star[0]}px; image-rendering: pixelated;`}
			/>
		{/each}
	</div>
	<div
		class="w-[1024px] lg:px-0 h-full flex lg:flex-row flex-col lg:items-center py-4 lg:py-8 gap-4 lg:gap-0 z-10 md:px-8 px-4"
	>
		<div class="flex flex-row items-center lg:justify-center justify-between space-x-4">
			<div>
				<LogoText />
				<h2 class="text-xs font-mono">
					v{version}
					{#if dev}
						DEV
					{/if}
				</h2>
			</div>
			<div class="ml-auto lg:hidden">
				<i
					class="bx bx-menu bx-md cursor-pointer anim-navbar-hamburger"
					onpointerdown={() => {
						animate('.anim-navbar-hamburger', {
							rotateZ: [0, 180],
							ease: createSpring()
						});
						menuVisible = !menuVisible;
					}}
					role="button"
					tabindex="0"
				></i>
			</div>
		</div>
		<div
			class={`lg:ml-auto lg:flex lg:flex-row flex-col lg:justify-end flex-wrap gap-2 lg:w-8/12 anim-navbar-tray ${menuVisible ? 'flex' : 'hidden'}`}
		>
			<Button text="🏠 Home" href="/" />
			<Button text="📝 Blog" href="/blog" />
			<Button text="📦 Projects" href="/projects" />
			<Button text="🎵 Music" href="/music" />
			<Button text="😀 My OC" href="/oc" />
			<Button text="⌨️ Gear" href="/gear" />
			<Button text="📱 Contact" href="/contact" />
			<Button text="💰 Donate" href="/donate" />
		</div>
	</div>
</nav>
