// src/components/feature/sideblocks/Block.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		title,
		children,
		disablePadding = false,
		disableBg = false,
		className = ''
	} = $props<{
		title: string;
		children?: Snippet;
		disablePadding?: boolean;
		disableBg?: boolean;
		className?: string;
	}>();
</script>

<div
	class={`${disableBg ? '' : 'bg-vi-800'} w-full rounded-lg min-w-[288px] shadow-[rgba(255,255,255,0.1)] border border-white/25 ${className}`}
>
	{#if title}
		<div class="flex items-center">
			<span class="font-normal text-sm px-4 py-2">
				{title}
			</span>
		</div>
	{/if}
	{#if title && children}
		<hr class="border-t border-t-vi-300" />
	{/if}
	{#if children}
		<div class={!disablePadding ? 'p-2' : ''}>{@render children()}</div>
	{/if}
</div>

// src/components/feature/sideblocks/Block.tsx
'use client'
import { ComponentChildren } from '@mae/misc/types'
import React, { Fragment } from 'react'

export default function SideBlock({children, title, disablePadding = false}: {title: string, disablePadding?: boolean, children?: ComponentChildren}) {
  return (
    <div className='flex flex-col w-full h-full rounded-lg shadow-[rgba(255,255,255,0.1)] border border-white/16'>
      <div className='flex items-center'>
        <span className='font-normal text-sm px-3 py-1'>
          {title}
        </span>
      </div>
      {
        children &&
        <Fragment>
          <hr className='border-t border-t-ctp-mauve'/>
          <div className={'h-full rounded-bl-md rounded-br-md overflow-hidden'}>{children}</div>
        </Fragment>
      }
    </div>
  )
}
