// src/components/feature/sideblocks/BlockClock.tsx
'use client';
import React from 'react'
import SideBlock from '@mae/components/feature/sideblocks/Block'
import { useDayjsCurrentTime } from '@mae/misc/useDayjsFormat'

export default function ClockBlock() {
  const time = useDayjsCurrentTime("HH:mm:ss");
  return (
    <SideBlock title="🕒 clock">
      <div className='text-sm flex flex-col items-center'>
        <span className='font-semibold text-3xl font-mono'>{time}</span>
        London, UK
      </div>
    </SideBlock>
  )
}

// src/components/feature/sideblocks/BlockClock.svelte
<script lang="ts">
	import Block from './Block.svelte';
	import dayjs from 'dayjs';
	import { onMount } from 'svelte';

	let time = $state(dayjs().format('HH:mm:ss'));
	onMount(() => {
		setTimeout(() => {
			time = dayjs().format('HH:mm:ss');
		}, 1000);
	});
</script>

<Block title="🕒 clock">
	<div class="text-sm flex flex-col items-center">
		<span class="font-semibold text-3xl font-mono">{time}</span>
		London, UK
	</div>
</Block>
