// src/components/feature/sideblocks/BlockLanyard.svelte
<script lang="ts">
	import { useLanyard } from 'svelte-lanyard';
	import Block from './Block.svelte';
	import { onMount } from 'svelte';
	import type { Readable } from 'svelte/store';

	let { id } = $props<{ id: string }>();

	const mediaProxyRegex = /mp:external\/[^\/]*\/(.*)/;

	// why does svelte-lanyard not export its types????
	let data:
		| Readable<{
				discord_status: string;
				spotify?: { album_art_url?: string; track_id: string; song: string; artist: string };
				activities: { application_id: number }[];
		  }>
		| undefined;
	let musicbee;

	onMount(() => {
		//@ts-ignore
		data = useLanyard(id);

		//@ts-ignore
		$data?.subscribe((value) => {
			musicbee = value.activities.find((a: any) => a.application_id === 409394531948298250);
		});
	});
</script>

{#if $data}
	{#if $data.discord_status != 'offline'}
		<Block title="🟢 online"></Block>
	{:else}
		<Block title="🌌 offline"></Block>
	{/if}

	{#if $data.spotify}
		<Block title="🎧 now playing">
			<div class="flex flex-row gap-2">
				{#if $data.spotify.album_art_url}
					<img src={$data.spotify.album_art_url} alt="Album art" width={48} height={48} class="" />
				{/if}
				<div class="flex flex-col justify-center">
					<a
						href={`https://open.spotify.com/track/${$data.spotify.track_id}`}
						class="text-white hover:underline"
					>
						<h2 class="text-sm font-medium">{$data.spotify.song}</h2>
					</a>
					<h3 class="text-xs">{$data.spotify.artist.replace(/;/g, ',')}</h3>
				</div>
			</div>
		</Block>
	{/if}
{:else}
	<Block title="⏳ connecting"></Block>
{/if}

// src/components/feature/sideblocks/BlockLanyard.tsx
'use client';
import React, { Fragment } from 'react'
import SideBlock from '@mae/components/feature/sideblocks/Block'
import {useLanyardWS} from 'use-lanyard';
import Image from "next/image";
import Link from 'next/link';

export default function LanyardBlock({id}: {id: `${bigint}`}) {
  const lanyard = useLanyardWS(id);
  if(!lanyard) return (
    <SideBlock title="⚠️ status server unreachable">
      <p className='text-sm text-center'>
        couldn't reach the status server ☹️
        <span className='h-4'></span>
        check if your browser + connection supports WebSockets
      </p>
    </SideBlock>
  );

  console.log(lanyard)

  const mediaProxyRegex = /mp:external\/[^\/]*\/(.*)/;
  const musicbee = lanyard.activities.find(a => a.application_id == "409394531948298250");

  return (
    <Fragment>
      {
        /* Online status*/
        lanyard.discord_status != 'offline' &&
        <SideBlock title="🟢 online">
        </SideBlock>
      }
      {
        /* Offline status*/
        lanyard.discord_status == 'offline' &&
        <SideBlock title="🌌 offline">
        </SideBlock>
      }
      {
        /* Spotify now playing */
        lanyard.spotify && 
        <SideBlock title="🎧 now playing">
          <div className='flex flex-row gap-2'>
            {
              lanyard.spotify.album_art_url &&
              <Image
                src={lanyard.spotify.album_art_url}
                alt="Album art"
                width={48}
                height={48}
                className='w-fit h-fit'
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
            }
            <div className="flex flex-col justify-center">
              <Link href={`https://open.spotify.com/track/${lanyard.spotify.track_id}`} className='text-white hover:underline'>
                <h2 className='text-sm font-medium'>{lanyard.spotify.song}</h2>
              </Link>
              <h3 className='text-xs'>{lanyard.spotify.artist.replace(/;/g, ",")}</h3>
            </div>
          </div>
        </SideBlock>
      }
      {
        /* MusicBee now playing */
        musicbee != null && 
        <SideBlock title="🎧 now playing">
          <div className='flex flex-row gap-2'>
            {
              musicbee.assets?.large_image && musicbee.assets?.large_image.startsWith("mp:external") &&
              <Image
                src={musicbee.assets?.large_image.match(mediaProxyRegex)![1].replace("https/", "https://")}
                alt="Album art"
                width={48}
                height={48}
                className='w-fit h-fit'
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
            }
            <div className="flex flex-col justify-center">
              <h2 className='text-sm font-medium'>{musicbee.details?.split("-")[1]}</h2>
              <h3 className='text-xs'>{musicbee.details?.split("-")[0]}</h3>
            </div>
          </div>
        </SideBlock>
      }
    </Fragment>
  );
}
