// src/components/feature/sideblocks/BlockSocial.tsx
'use client';
import Link from 'next/link';
import { Tooltip } from 'react-tooltip';

export default function SocialSpeeddial({href, tooltipContent, tooltipId, icon}: {href: string, tooltipContent: string, tooltipId: string, icon: string}) {
  return (
    <Link href={href} data-tooltip-content={tooltipContent} data-tooltip-id={tooltipId} className='text-white' aria-label={tooltipContent}>
      <Tooltip id={tooltipId} style={{fontSize: "0.875rem", lineHeight: "1.25rem"}} />
      <i className={`bx ${icon} hover:scale-110 hover:text-ctp-mauve transition-all duration-75 active:scale-90`}></i>
    </Link>
  )
}

export function SocialSpeeddialSvg({href, tooltipContent, tooltipId, children}: {children: React.ReactNode; href: string, tooltipContent: string, tooltipId: string}) {
    return (
      <Link href={href} data-tooltip-content={tooltipContent} data-tooltip-id={tooltipId} className='text-white' aria-label={tooltipContent}>
        <Tooltip id={tooltipId} style={{fontSize: "0.875rem", lineHeight: "1.25rem"}} />
        <div className={`hover:scale-110 hover:text-ctp-mauve transition-all duration-75 active:scale-90 w-[36px] h-[40.5px] flex justify-center`}>
            {children}
        </div>
      </Link>
    )
  }

// src/components/feature/sideblocks/BlockSocial.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let { href, tooltipContent, tooltipId, children } = $props<{
		href: string;
		tooltipContent: string;
		tooltipId: string;
		children: Snippet;
	}>();
</script>

<a
	{href}
	data-tooltip-content={tooltipContent}
	data-tooltip-id={tooltipId}
	class="text-white"
	aria-label={tooltipContent}
>
	<!-- <Tooltip id={tooltipId} style={{ fontSize: '0.875rem', lineHeight: '1.25rem' }} /> -->
	<div
		class={`hover:scale-110 hover:text-ctp-mauve transition-all duration-75 active:scale-90 w-[36px] h-[40.5px] flex justify-center`}
	>
		{@render children()}
	</div>
</a>
