// src/components/core/Navbar.svelte
<script lang="ts">
	import { animate, createSpring } from 'animejs';
	import Button from '@mae/components/ui/Button.svelte';
	import LogoText from '@mae/components/brand/LogoText.svelte';
	import { version, dev } from '$app/environment';
	import { debounce } from '$lib/misc/utils';

	// TODO MAKE STARS

	let bar: HTMLElement;

	let isTransparentPage = false; // TODO: STORE
	let menuVisible = $state(false); // TODO: IMPLEMENT
	let stars = $state<number[][]>([]);
	let starsDone = $state(false);

	const _generateStars = () => {
		console.log('✨');
		if (!bar) return;
		const width = bar.offsetWidth;
		const height = bar.offsetHeight;

		let newStars = [];
		for (let i = 0; i < 8; i++) {
			let star = Math.floor(Math.random() * 4);
			let randX = Math.floor(Math.random() * (width - 16)) + 0;
			let randY = Math.floor(Math.random() * (height - 16));
			newStars.push([randX, randY, star]);
		}
		stars = newStars;
	};

	const generateStars = debounce(() => {
		_generateStars();
	}, 50);

	$effect(() => {
		if (!starsDone) {
			window.addEventListener('resize', () => {
				generateStars();
			});
			generateStars();
		}
	});
</script>

<nav
	class={`w-full lg:h-32 flex justify-center z-20 sticky ${isTransparentPage ? 'bg-transparent' : 'bg-vi-900'}`}
	bind:this={bar}
>
	<div
		class="absolute top-0 left-0 lg:w-[1024px] w-full opacity-60 z-0 text-clip"
		aria-hidden={true}
	>
		{#each stars as star, i}
			<img
				src={`/assets/stars/star_${star[2]}.png`}
				width={16}
				height={16}
				alt="star"
				class={'absolute ' + `anim_star`}
				style={`top: ${star[1]}px; left: ${star[0]}px; image-rendering: pixelated;`}
			/>
		{/each}
	</div>
	<div
		class="w-[1024px] lg:px-0 h-full flex lg:flex-row flex-col lg:items-center py-4 lg:py-8 gap-4 lg:gap-0 z-10 md:px-8 px-4"
	>
		<div class="flex flex-row items-center lg:justify-center justify-between space-x-4">
			<div>
				<LogoText />
				<h2 class="text-xs font-mono">
					v{version}
					{#if dev}
						DEV
					{/if}
				</h2>
			</div>
			<div class="ml-auto lg:hidden">
				<i
					class="bx bx-menu bx-md cursor-pointer anim-navbar-hamburger"
					onpointerdown={() => {
						animate('.anim-navbar-hamburger', {
							rotateZ: [0, 180],
							ease: createSpring()
						});
						menuVisible = !menuVisible;
					}}
					role="button"
					tabindex="0"
				></i>
			</div>
		</div>
		<div
			class={`lg:ml-auto lg:flex lg:flex-row flex-col lg:justify-end flex-wrap gap-2 lg:w-8/12 anim-navbar-tray ${menuVisible ? 'flex' : 'hidden'}`}
		>
			<Button text="🏠 Home" href="/" />
			<Button text="📝 Blog" href="/blog" />
			<Button text="📦 Projects" href="/projects" />
			<Button text="🎵 Music" href="/music" />
			<Button text="😀 My OC" href="/oc" />
			<Button text="⌨️ Gear" href="/gear" />
			<Button text="📱 Contact" href="/contact" />
			<Button text="💰 Donate" href="/donate" />
		</div>
	</div>
</nav>

// src/components/layout/Navbar.tsx
'use client';
import anime from 'animejs';
import Link from 'next/link'
import { useEffect, useRef, useState } from 'react'
import Button from '@mae/components/Button';
import Image from 'next/image';
import _ from 'lodash';
import { usePathname } from 'next/navigation';
import { useRecoilState } from 'recoil';
import { transparentNavbar } from '@mae/store/transparentNavbar';

export default function Navbar({version}: {version: string}) {
  const pathname = usePathname();
  const [isTransparentPage, setTransparentPage] = useRecoilState(transparentNavbar);

  // when navigating to a new page, set the transparent state to default
  useEffect(() => {
    setTransparentPage(false)
  }, [pathname])

  const bar = useRef<HTMLDivElement>(null);
  const [stars, setStars] = useState<number[][]>([]);
  const [starsDone, setStarsDone] = useState(false);
  const [menuVisible, setMenuVisible] = useState(false);

  const _generateStars = () => {
    console.log("✨")
    const width = bar.current!.offsetWidth
    const height = bar.current!.offsetHeight

    let newStars = []
    for(let i = 0; i < 8; i++) {
      let star = Math.floor(Math.random() * (4));
      let randX = Math.floor(Math.random() * (width - 16)) + 0;
      let randY = Math.floor(Math.random() * (height - 16));
      newStars.push([randX, randY, star])
    }
    setStarsDone(true)
    setStars(stars.concat(newStars))
  }

  const generateStars = _.debounce(() => {
    _generateStars()
  }, 50)

  useEffect(() => {
    if(!starsDone) {
      window.addEventListener('resize', () => {
        generateStars()
      })
      generateStars()
    }

    if(menuVisible) {
      anime({
        targets: ".anim-navbar-tray a",
        translateX: [-50, 0],
        delay: anime.stagger(50),
        opacity: [0, 1],
      })
    }
  }, [bar, menuVisible])

  return (
    <div className={`w-full lg:h-32 flex justify-center z-20 sticky ${(isTransparentPage) ? 'bg-transparent' : 'bg-neutral-900'}`} ref={bar}>
      <div className="absolute top-0 left-0 lg:w-[1024px] w-full opacity-60 z-0 text-clip">
        {
          stars.map((star, i) => (
            <Image 
            src={`/assets/stars/star_${star[2]}.png`}
            width={16} 
            height={16} 
            alt="star" 
            className={'absolute ' + `anim_star`} 
            style={{top: star[1], left: star[0], imageRendering: "pixelated"}}
            key={"star_" + i}/>
          ))
        }
      </div>
      <div className='w-[1024px] px-4 lg:px-0 h-full flex lg:flex-row flex-col lg:items-center py-4 lg:py-8 gap-4 lg:gap-0 z-10'>
        <div className='flex flex-row items-center lg:justify-center justify-between space-x-4'>
          <div>
            <Link href='/'>
              <LogoText/>
            </Link>
            <h6 className='text-xs font-mono'>v{version}</h6>
          </div>
          <div className='ml-auto lg:hidden'>
            <i className='bx bx-menu bx-md cursor-pointer anim-navbar-hamburger' onClick={() => { 
              anime({
                targets: ".anim-navbar-hamburger",
                rotateZ: [0, 180]
              })
              setMenuVisible(!menuVisible) 
            }}></i>
          </div>
        </div>
        <div className={`lg:ml-auto lg:flex lg:flex-row flex-col lg:justify-end flex-wrap gap-2 lg:w-8/12 anim-navbar-tray ${(menuVisible) ? 'flex' : 'hidden'}`}>
          <Button text="🏠 Home" href="/"/>
          <Button text="📦 Projects" href="/projects"/>
          <Button text="🎵 Music" href="/music"/>
          <Button text="😀 My OC" href="/oc"/>
          <Button text="💻 Services" href="/services"/>
          <Button text="📝 Blog" href="/blog"/>
          <Button text="💰 Donate" href="/donate"/>
          <Button text="📱 Contact" href="/contact"/>
          <Button text="⌨️ Gear" href="/gear"/>
        </div>
      </div>
    </div>
  )
}

function LogoText() {
  return (
    <h3 className='font-bold text-5xl tracking-tighter text-white' data-anim="logo">mae</h3>
  )
}
