// src/components/core/PageHeader.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let { title, children } = $props<{
		title: string;
		children?: Snippet;
	}>();
</script>

<div class="space-y-2">
	<h1 class="font-bold text-4xl">
		{title}
	</h1>
	<p class="text-md">
		{#if children}
			{@render children()}
		{/if}
	</p>
</div>

// src/components/layout/PageHeader.tsx
import React, { ReactNode } from 'react'

export default function PageHeader({title, children}: {title: string; children: ReactNode[] | ReactNode}) {
  return (
    <div className='space-y-2'>
      <h1 className='font-bold text-4xl'>
        { title }
      </h1>
      <h3 className='text-md'>
        { children }
      </h3>
    </div>
  )
}
