// src/components/misc/WebBadge.svelte
<script lang="ts">
	let {
		href = null,
		src,
		alt
	} = $props<{
		href?: string;
		src: string;
		alt: string;
	}>();
</script>

<!-- TODO: deduplicate -->

{#if href != null}
	<a {href}>
		<img
			{src}
			width={88}
			height={31}
			alt={alt || 'Web badge'}
			style="image-rendering: pixelated;"
			class="hover:-translate-x-1 hover:-translate-y-1 transition-transform"
		/>
	</a>
{:else}
	<img
		{src}
		width={88}
		height={31}
		alt={alt || 'Web badge'}
		style="image-rendering: pixelated;"
		class="hover:-translate-x-1 hover:-translate-y-1 transition-transform"
	/>
{/if}

// src/components/WebBadge.tsx
'use client';
import React from 'react'
import Image from 'next/image';
import Link from 'next/link';

interface WebBadgeProps {
  href?: string;
  src: string;
  alt: string;
}

export default function WebBadge(props: WebBadgeProps) {
  return (
    <Link href={props.href || "#"}>
      <Image src={props.src} width={88} height={31} alt={props.alt || "Web badge"} quality={100} style={{ imageRendering: 'pixelated' }} className='hover:-translate-x-1 hover:-translate-y-1 transition-transform'></Image>
    </Link>
  )
}
