// src/app/gear/page.tsx
import PageContainer from '@mae/components/layout/PageContainer'
import PageHeader from '@mae/components/layout/PageHeader'
import React from 'react'
import Image from 'next/image';

export default function GearPage() {
  return (
    <PageContainer>
      <PageHeader title="⌨️ gear">
        the stuff i use to make stuff
      </PageHeader>

      <div className='flex flex-row justify-between'>
        <div className='space-y-4 flex-grow'>
          <h2 className='font-semibold text-2xl'>Software</h2>
          <h4>📽️ for videos:</h4>
          <ul className='list-disc list-inside'>
            <li>Blender</li>
            <li>Premiere Pro</li>
            <li>After Effects</li>
            <li>Aseprite</li>
          </ul>
          
          <h4>👩‍💻 for code:</h4>
          <ul className='list-disc list-inside'>
            <li>Visual Studio Code</li>
            <li>Visual Studio 2022</li>
            <li>IntelliJ Idea</li>
            <li>Termius</li>
            <li>Git</li>
          </ul>

          <h4>🎵 for music:</h4>
          <ul className='list-disc list-inside'>
            <li><b>Ableton Live</b></li>
            <li><b>FL Studio</b></li>
            <li>Xfer Serum</li>
            <li>Kilohearts Phase Plant</li>
            <li>Vital</li>
            <li>Spitfire LABS</li>
            <li>Spitfire BBC Symphony Orchestra</li>
            <li>ValhallaVintageVerb</li>
            <li>ValhallaSupermassive</li>
          </ul>
          <p className='text-sm'>and a lot of other VSTs..</p>
        </div>
        <div className='h-auto w-1/2 gap-8 hidden lg:grid'>
          <div className='relative'>
            <Image src="/assets/ableton_screenshot.png" fill={true} className='rounded-xl object-cover object-top' alt="Screenshot of Ableton Live"></Image>
          </div>
          <div className='relative'>
            <Image src="/assets/code_screenshot.png" fill={true} className='rounded-xl object-cover object-center' alt="Screenshot of Visual Studio Code"></Image>
          </div>
        </div>
      </div>

      <hr/>
      <div className='h-80 w-full relative'>
        <Image src="/assets/pc.jpg" fill={true} alt="mae computer" className='rounded-xl object-cover object-center'></Image>
      </div>
      <div className='flex justify-around'>
        <div className='space-y-2'>
          <h2 className='font-semibold text-2xl'>Main Computer</h2>
          <ul className='list-inside'>
            <li><i className='bx bx-chip'></i> Intel Core i7-9700k</li>
            <li><i className='bx bx-microchip'></i> 2x8GB Corsair Vengeance @ 3000MHz</li>
            <li><i className='bx bx-microchip'></i> NVIDIA GeForce GTX 1070</li>
            <li><i className='bx bx-microchip'></i> MSI Z370-A PRO</li>
            <li><i className='bx bx-hdd'></i> 240GB SSD</li>
            <li><i className='bx bx-hdd'></i> 480GB SSD</li>
            <li><i className='bx bx-hdd'></i> 1TB HDD</li>
            <li><i className='bx bx-hdd'></i> 1TB HDD (external)</li>
            <li><i className='bx bx-hdd'></i> 2TB HDD (external)</li>
            <li><i className='bx bx-wind'></i> DEEPCOOL AK620 WH</li>
            <li><i className='bx bx-box'></i> NZXT H5 Flow</li>
            <li><i className='bx bx-disc'></i> Windows 11 Pro</li>
          </ul>
        </div>
        <div className='space-y-2'>
          <h2 className='font-semibold text-2xl'>Accessories</h2>
          <ul className='list-disc list-inside'>
            <li>Custom Keyboard</li>
            <li>Logitech G402 Mouse</li>
            <li>Steelseries Arctis 3 Headphones</li>
            <li>M-Audio M-Track 2x2 Audio Interface</li>
            <li>Neewer NW-700 Microphone</li>
          </ul>
          <h2 className='font-semibold text-2xl'>Misc</h2>
          <ul className='list-disc list-inside'>
            <li>Nintendo Switch Pro Controller</li>
            <li>DualShock 4</li>
            <li>Oculus Quest 2</li>
            <li>Alesis VI49</li>
            <li>Launchpad Pro</li>
          </ul>
        </div>
      </div>
    </PageContainer>
  )
}

// src/routes/(main)/gear/+page.svelte
<script>
	import PageContainer from '@mae/components/core/PageContainer.svelte';
	import PageHeader from '@mae/components/core/PageHeader.svelte';

	import ImgStargazer from '@mae/assets/img/computers/stargazer.jpg';
	import ImgNebula from '@mae/assets/img/computers/nebula.png';
	import ImgAurora from '@mae/assets/img/computers/aurora.png';
</script>

<PageContainer>
	<PageHeader title="⌨️ gear">the stuff i use to make stuff</PageHeader>

	<h2 class="font-semibold text-5xl">computers</h2>

	<!-- {/* stargazer */} -->
	<div class="grid grid-rows-2 sm:grid-rows-1 sm:grid-cols-2 min-h-64">
		<div class="space-y-2">
			<h3 class="font-semibold text-4xl">💫 stargazer</h3>

			<i>my main computer! evolving since 2019</i>
			<ul class="list-inside">
				<li>
					<i class="bx bx-chip"></i> Intel Core i7-9700k
				</li>
				<li>
					<i class="bx bx-microchip"></i> 2x8GB Corsair Vengeance @ 3000MHz
				</li>
				<li>
					<i class="bx bx-microchip"></i> NVIDIA GeForce GTX 1080
				</li>
				<li>
					<i class="bx bx-microchip"></i> MSI Z370-A PRO
				</li>
				<li>
					<i class="bx bx-hdd"></i> 240GB SSD
				</li>
				<li>
					<i class="bx bx-hdd"></i> 480GB SSD
				</li>
				<li>
					<i class="bx bx-hdd"></i> 1TB HDD
				</li>
				<li>
					<i class="bx bx-hdd"></i> 1TB HDD (external)
				</li>
				<li>
					<i class="bx bx-hdd"></i> 2TB HDD (external)
				</li>
				<li>
					<i class="bx bx-wind"></i> DEEPCOOL AK620 WH
				</li>
				<li>
					<i class="bx bx-box"></i> NZXT H5 Flow
				</li>
				<li>
					<i class="bx bx-disc"></i> Windows 11 Pro
				</li>
			</ul>
		</div>

		<div class="relative">
			<img
				src={ImgStargazer}
				alt="A computer tower with lights"
				class="object-cover rounded-lg shadow-mae"
			/>
		</div>
	</div>

	<!-- {/* nebula */} -->
	<div class="grid grid-rows-2 sm:grid-rows-1 sm:grid-cols-2 min-h-64">
		<div class="space-y-2">
			<h3 class="font-semibold text-4xl">🌃 nebula</h3>

			<i>my laptop</i>
			<ul class="list-inside">
				<li>
					<i class="bx bx-laptop"></i> 2023 MacBook Pro
				</li>

				<li>
					<i class="bx bx-chip"></i> Apple M2 Pro
				</li>

				<li>
					<i class="bx bx-microchip"></i> 16GB RAM
				</li>

				<li>
					<i class="bx bx-microchip"></i> 512GB storage
				</li>
			</ul>
		</div>

		<div class="relative">
			<img
				src={ImgNebula}
				alt="A MacBook with the text 'i am nebula and i am hiding all the secrets' displayed in a TextEdit window"
				class="object-cover rounded-lg shadow-mae"
			/>
		</div>
	</div>

	<!-- {/* aurora */} -->
	<div class="grid grid-rows-2 sm:grid-rows-1 sm:grid-cols-2 min-h-64">
		<div class="space-y-2">
			<h3 class="font-semibold text-4xl">🌌 aurora</h3>

			<i>my home server made out of spare parts!</i>
			<ul class="list-inside">
				<li>
					<i class="bx bx-chip"></i> AMD Ryzen 5 1600
				</li>

				<li>
					<i class="bx bx-microchip"></i> 8GB RAM
				</li>

				<li>
					<i class="bx bx-microchip"></i> NVIDIA GeForce GTX 1070
				</li>

				<li>
					<i class="bx bx-hdd"></i> 4TB storage total
				</li>

				<li>
					<i class="bx bx-disc"></i> Proxmox (Debian)
				</li>
			</ul>
		</div>

		<div class="relative">
			<img
				src={ImgAurora}
				alt="The internals of a tower computer on the floor"
				class="object-cover rounded-lg shadow-mae"
			/>
		</div>
	</div>

	<!-- {/* misc */} -->
	<div class="space-y-2 grid grid-cols-2">
		<div>
			<h3 class="font-semibold text-2xl">Accessories for stargazer</h3>
			<ul class="list-disc list-inside">
				<li>Custom Keyboard (gateron yellows)</li>
				<li>Logitech G Pro Superlight Mouse</li>
				<li>Beyerdynamic DT 990 Pro Headphones</li>
				<li>M-Audio M-Track 2x2 Audio Interface</li>
				<li>some cheap mic off amazon lmao</li>
			</ul>
		</div>
		<div>
			<h3 class="font-semibold text-2xl">Misc</h3>
			<ul class="list-disc list-inside">
				<li>Oculus Quest 2 for VR (i use a cheap link cable and a kiwi design headstrap)</li>
				<li>Alesis VI49 and Launchpad Pro for MIDI controllers</li>
			</ul>
		</div>
	</div>

	<!-- {/* software */} -->
	<hr />
	<div class="flex flex-row justify-between">
		<div class="space-y-4 flex-grow">
			<h3 class="font-semibold text-4xl">Software</h3>
			<h4 class="font-semibold text-xl">🎵 for music:</h4>
			<ul class="list-disc list-inside">
				<li>Ableton Live Suite</li>
				<li>FL Studio</li>

				<li>Kilohearts stuff (phase plant)</li>
				<li>vital</li>
				<li>spitfire LABS / orchestra</li>
				<li class="text-sm">lots of other plugins</li>
			</ul>

			<h4 class="font-semibold text-xl">📽️ for videos:</h4>
			<ul class="list-disc list-inside">
				<li>Blender</li>
				<li>Premiere Pro</li>
				<li>After Effects</li>
				<li>Aseprite</li>
			</ul>

			<p class="text-sm">among others</p>
		</div>
		<div class="h-auto w-1/2 gap-8 hidden lg:grid">
			<div class="relative">
				<img
					src="/assets/ableton_screenshot.png"
					class="rounded-xl object-cover object-top"
					alt="Screenshot of Ableton Live"
				/>
			</div>
			<div class="relative">
				<img
					src="/assets/code_screenshot.png"
					class="rounded-xl object-cover object-center"
					alt="Screenshot of Visual Studio Code"
				/>
			</div>
		</div>
	</div>
</PageContainer>
