// src/components/Button.tsx
'use client'
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import React from 'react'
import {Howl, Howler} from 'howler';

const soundClick = new Howl({
  src: ['/assets/sfx/click.wav'],
  volume: 0.2
});

export default function Button({text, href, className, icon, onClick}: {text: string; href: string; className?: string; icon?: string; onClick?: () => any;}) {
  const pathname = usePathname();

  const playSound = () => {
    if(onClick) onClick();
    soundClick.play()
  }


  if(onClick) {
    let href = null;
  }

  return (
    <Link href={href} onClick={playSound}>
      <h3 className={
        `${(pathname == href) ? 'bg-purple-500 hover:bg-purple-400 text-white' : 'bg-neutral-800 hover:bg-neutral-700'} select-none transition-all py-1 px-4 rounded-md active:scale-90 text-white ${className}`
        }>
        {icon && <i className={icon}></i>}
        {text}
      </h3>
    </Link>
  )
}

// src/components/ui/Button.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { Howl } from 'howler';
	let { className = '', href = null, icon = null, text, onclick = null } = $props();

	const soundClick = new Howl({
		src: ['/assets/sfx/click.wav'],
		volume: 0.2
	});

	const onButtonPress = () => {
		if (onclick) onclick();
		soundClick.play();
	};

	if (onclick) {
		href = null;
	}

	let pathname = $derived(page.url.pathname);
</script>

<a
	{href}
	onclick={onButtonPress}
	class="{pathname == href
		? 'bg-vi-300 text-vi-800 font-semibold'
		: `bg-vi-700 hover:bg-vi-600 text-white`} select-none transition-all duration-75 ease-out py-1 px-4 rounded-md active:scale-90 cursor-pointer {className}"
>
	{#if icon}
		<i class={icon}></i>
	{/if}
	{text}
</a>
